#BACKUP ETCD EMBEDDED OSE
- hosts: masters
  become: yes
  gather_facts: no
  tasks:

  - name: Cluster pre check
    lineinfile:
      dest: /etc/etcd/etcd.conf
      regexp: '^ETCD_INITIAL_CLUSTER_STATE=new'
      line: 'ETCD_INITIAL_CLUSTER_STATE=existing'

  - name: Backup directory
    file: 
      path: /ose_cluster_backup
      state: directory 
      mode: 0744

  - name: Backup origin and etcd config directories
    shell: "{{ item }}"
    with_items:
      - tar czvf /ose_cluster_backup/openshift-$(hostname -f).tgz /etc/origin
      - tar czvf /ose_cluster_backup/etcd-config-$(hostname -f).tgz /etc/etcd

#BACKUP OF ETCD DATA DIRECTORY  
- hosts: master1
  become: yes
  gather_facts: no
  tasks:
 
  - name: Automated etcd data directory backup
    script: ../scripts/backup_etcd.sh
 
